config/routes.rb
Rails.application.routes.draw do

 get 'contact' => 'messages#new', as: 'contact'
  post 'contact' => 'messages#create'

  get 'index' => 'static_pages#index', as: 'index'
  get 'about' => 'static_pages#about', as: 'about'

  get 'profile' => 'users#profile', as: 'profile'

  get 'users/index'

  get 'users/show'

  delete 'horses/:horse_id/horse_weights/:id' => 'horse_weights#destroy', as: 'delete'
  resources :horse_weights
  resources :tasks
  resources :horses 
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations'}
  root 'static_pages#index'

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :horses, dependent: :destroy
  has_many :tasks, through: :horses
  after_create :send_welcome_email
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :zipcode, presence: true
  # validates :email, :password, :zipcode, presence: true

  private
    def send_welcome_email
      UserMailer.welcome_email(self).deliver_now
    end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
 before_filter :configure_sign_up_params, only: [:create]
 before_filter :configure_account_update_params, only: [:update]



  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

   protected

  # You can put the params you want to permit in the empty array.
  def configure_sign_up_params
    devise_parameter_sanitizer.for(:sign_up) << :zipcode
  end

  # You can put the params you want to permit in the empty array.
  def configure_account_update_params
    devise_parameter_sanitizer.for(:account_update) << :zipcode
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def profile
    @user = current_user
    # @assigned_tasks = Task.where(assigned_user_id: current_user)
    # @tasks = Task.find_by(params[:task_id])
    
    @tasks = []
    current_user.tasks.each_index do |index|
      if index < 3
        @tasks.push(current_user.tasks[index])
      end
    end

    @horses = []
    @tasks.each do |task|
      @horses.push(Horse.find(task.horse_id))
    end
  end

  def index
    @users = User.all
  end

  def show

  end
  
  private

  def user_params
    params.require(:user).permit(:email, :password, :zipcode)
  end

end

app/views/users/index.html.erb
<h1> Test users index </h1>

<%= Weathermanager.new.get_precipitation_chance(98101) %>

app/views/users/profile.html.erb
<style type="text/CSS">

body {
  background-image: url(/assets/06.jpg);
  background-repeat: repeat-y;
  background-size: 100%;
  z-index: 0px;
  background-color: #EAE7E5;
  color: black;
  background-position: center;
  }

  .col-xs-11.col-md-7 {
    background: rgba(234, 231, 229, 0.7);
    margin: 5px;
    padding-bottom: 10px;
    min-height: 300px;
    
  }

  .col-xs-11.col-md-4 {
    background: rgba(234, 231, 229, 0.7);
    margin: 5px;
    color: #6E4D51;
    padding-bottom: 20px;
  }


</style>

<div class="row">
  <div class="col-xs-11 col-md-7">
  <!-- Task table -->
      <div class="tasks">
        <h2>Upcoming Appointments</h2>  
        <table class = 'table'>
          <thead>
            <tr>
              <th>Horse</th>
              <th>Appointment</th>
              <th>Description</th>
              <th>DueDate</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @tasks.each_with_index do |task, index| %>
              
                <tr>
                  <td><%= @horses[index].name %></td>
                  <td><%= task.name %></td>
                  <td><%= task.description %></td>
                  <td><%= task.duedate %></td> 
                  <td>

                  <div class="btn-group btn-group-xs">
                  <%= link_to 'Edit', edit_task_path(task), remote: true, class: "btn btn-default" %>  
                  <%= link_to 'Delete', task, data: { confirm: "Are you sure you wish to delete this task?" },
                                                         method: :delete, class: "btn btn-default" %>
                  </div>
                  </td>  
                </tr>
              <% end %>
          </tbody>
        </table>

      </div>
      <center>
      <%= link_to "New Appointment", new_task_path, remote: true, class: "btn btn-default" %>
      </center>
      </div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">HtH</h4>
      </div>
      <div class="modal-body">
      </div>
<!--       <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div> -->
    </div>
  </div>
</div>      

    <!-- Horse Table -->
  <div class="col-xs-11 col-md-4">
    <h2>Your horses</h2> 
    <table class="table">
      <thead>
        <tr>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% if @user.horses.any? %>
          <% @user.horses.each do |horse| %> 
             <tr> 
             <td><%= image_tag horse.pic.url(:thumb) %></td>
              <td> <%= link_to horse.name, horse_path(horse) %> </td>
              <td>  
                <div class="btn-group btn-group-xs">
                  <% if user_signed_in? && current_user.id == horse.user_id %>
                  <%= link_to 'Edit', edit_horse_path(horse), remote: true, class: "btn btn-default" %>                
                  <%= link_to 'Delete', horse, data: { confirm: "Are you sure you wish to delete this horse?" }, 
                                                 method: :delete, class: "btn btn-default" %>
                  <% end %>
                </div>  
              </td>
            </tr>
          <% end %> 
        <% end %>
      </tbody>
    </table>
    <center>
    <%= link_to "New Horse", new_horse_path, remote: true, class: "btn btn-default" %>
    </center>
   </div>
</div>  

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

HTTParty.get("http://api.worldweatheronline.com/free/v2/weather.ashx?q=London&format=json&num_of_days=1&tp=24&key=31f6ddb631ced9c600aad9ab924d7")