config/routes.rb
Rails.application.routes.draw do

 get 'contact' => 'messages#new', as: 'contact'
  post 'contact' => 'messages#create'

  get 'index' => 'static_pages#index', as: 'index'
  get 'about' => 'static_pages#about', as: 'about'

  get 'profile' => 'users#profile', as: 'profile'

  get 'users/index'

  get 'users/show'

  delete 'horses/:horse_id/horse_weights/:id' => 'horse_weights#destroy', as: 'delete'
  resources :horse_weights
  resources :tasks
  resources :horses 
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations'}
  root 'static_pages#index'

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

end

app/models/horse_weight.rb
class HorseWeight < ActiveRecord::Base
  belongs_to :horses
  validates :horse_id, :weight, presence: true 
end

app/controllers/horse_weights_controller.rb
class HorseWeightsController < ApplicationController


  def index
  end

  def show
    @horse_weight = HorseWeight.find(params[:id])
  end

  def new

    @horse = Horse.find(params[:id])
    @horse_weight = HorseWeight.new
    respond_to do |format|
        format.html
        format.js
    end     

  end

  def create
    @horse_weight = HorseWeight.new(horse_weights_params)
      if @horse_weight.save
      flash[:success] = "Weight updated"
      redirect_to horse_path(@horse_weight.horse_id) 
    else
      flash[:danger] = "Please fill in the field."
      render :new
    end
  end

  def destroy
    @horse_weight = HorseWeight.find(params[:id])
    # if current_user.id == @horse.user_id
    @horse_weight.destroy
      redirect_to horse_path(@horse_weight.horse_id)
    #else
     #redirect_to profile_path
    #end
  end

  private

  def horse_weights_params
    params.require(:horse_weight).permit(:weight, :horse_id)
  end
end

app/views/horse_weights/_form_weight.erb
<%= form_for @horse_weight do |f| %>
  <%= render 'devise/shared/error_messages', object: f.object %>  
  <div class="field">
    <%= f.label :weight %><br>
    <%= f.number_field :weight %>
  </div>

  <div class="field">
    <%= f.hidden_field :horse_id, value: @horse.id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

<div class="row">
  <table class="table">
    <% @horse.horse_weights.each do|weight| %>
    <tr>
    <td> <%= weight.weight %> </td>
    <td> <%= weight.created_at %></td>
    <td> <%= link_to 'Delete', delete_path(@horse, weight), data: { confirm: "Are you sure?" }, method: :delete, class: "btn btn-danger" %> </td>
    </tr>
  <% end %>
</div>

app/views/horse_weights/new.html.erb
<%= render 'form_weight' %>

app/views/horse_weights/new.js.erb
$('#myModalLabel').html('<%= j render partial: "form_weight", locals: { horse: @horse } %>');
$('#myModal').modal('show');

app/views/horse_weights/show.html.erb
<div class="row">
  <table class="table">
    <% @horse.horse_weights.each do|weight| %>
    <tr>
    <td> <%= weight.weight %> </td>
    <td> <%= weight.created_at %></td>
    <td> <%= link_to 'Delete', delete_path(@horse, weight), data: { confirm: "Are you sure?" }, method: :delete, class: "btn btn-danger" %> </td>
    </tr>
  <% end %>
</div>