config/routes.rb
Rails.application.routes.draw do

 get 'contact' => 'messages#new', as: 'contact'
  post 'contact' => 'messages#create'

  get 'index' => 'static_pages#index', as: 'index'
  get 'about' => 'static_pages#about', as: 'about'

  get 'profile' => 'users#profile', as: 'profile'

  get 'users/index'

  get 'users/show'

  delete 'horses/:horse_id/horse_weights/:id' => 'horse_weights#destroy', as: 'delete'
  resources :horse_weights
  resources :tasks
  resources :horses 
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations'}
  root 'static_pages#index'

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

end

app/views/layouts/_footer.html.erb
<style type="text/CSS">
body {
  height: 100%;
}
#footer {
  position: absolute;
  width: 100%;
  height: 60px;
  margin-top: 20px;
  padding-top: 20px;
  background-color: #eeeeee;
}
/* Links */
/* unvisited link */
a:link {
    color: #6E4D51;
}

/* visited link */
a:visited {
    color: #6E4D51;
}

/* mouse over link */
a:hover {
    color: #CEBCB9;
}

/* selected link */
a:active {
    color: #777;
  }
</style>

<body>
    <div class="container">
      <div align="center">
        <a href="/">Home</a> | <a href="/about">About</a> | <a href="/contact">Contact</a> | <a href="http://www.devpointlabs.com/" target="_blank">DevPoint Labs</a>
      </div><br>
    </div>
</body>

app/views/layouts/_header.html.erb
<style type="text/CSS">

  .navbar.navbar-default {
    margin-top: 0px;
    height: auto;
  }
  .col-xs-10 {
    width: 100%;
  }
  .notice {
    color: white;
    padding-bottom: 0px;
    margin-top: white;
  }
  .allert {
    color: white;
    padding-bottom: 0px;
    margin-top: white;
  }
  .nav.navbar-nav {
    margin-top: 45px; 
  }
</style>


<div class="row">

</div>
<nav class="navbar navbar-default" role="navigation" >
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><%= image_tag("logo.png") %><br></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/about">About<span class="sr-only">(current)</span></a></li>
        <li><a href="/contact">Contact</a></li>
        <li><a target="_blank" href="http://www.devpointlabs.com">DPL</a></li>
        <%if user_signed_in?%>
        <li><%= link_to "Your Barn", profile_path %></li>
        <% end %>
      
      </ul>
      <ul class="nav navbar-nav navbar-right">

        
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Account <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <% if user_signed_in? %>

            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            <li><%= link_to "Edit Your Profile", edit_user_registration_path %></li>
            <% else %>
            <li><%= link_to "Sign up", new_user_registration_path %></li>
            <li><%= link_to "Sign in", new_user_session_path %></li>
            <% end %>
<!--             <% if user_signed_in? %>  
            <li class="divider"></li>
            <li><%= link_to "Your Barn", profile_path %></li>
            <% end %> -->
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HeedTheHerd</title>
  <link href='https://fonts.googleapis.com/css?family=Walter+Turncoat' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="header">
    <%= render 'layouts/header' %>
  </div>

  <div id="content">
    <div class="container"> 
      <%= yield %>
    </div>
  </div>

  <div id="push"></div>

  <div id="footer">
    <%= render 'layouts/footer' %>
  </div>

</body>
</html>